language: node_js

node_js:
  - 6.6
  - 6.0
  - 5.0
  - 4.0
  - 0.12
  - 0.10

before_install:
  - curl https://install.meteor.com | /bin/sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Add testing package since it's not currently enabled in Telescope
  - printf "sanjo:jasmine@0.11.0" >> .meteor/packages

notifications:
  slack: hackingdays:ZyYyrtimTCCZISUFanYs20bH